FILES_PATH: /home/nico/workspace/Livebox-wifi-stats/files_to_send/st_1/
STATIONS:
- name: Android1_AC_BD_70_27_CA_19
  ip: 192.168.1.12
  ssh_user: nico
  ssh_password: nico
  protocol: sftp
  operative_system: Android
  port: 2233
  initial_data_rate_in_kbps: 0
  throughput_increment_in_kbps: 1000
  initial_dead_time_in_secs: 2
  transfer_nb_per_step: 1
  send_interval_in_secs: 0.01
