COLUMNS:
  - txframe
  - txbyte
  - txretrans
  - txlost
  - txfail
  - txdatamcast
  - txdatabcast
  - txdropped
  - txprshort
  - txdmawar
  - txnobuf
  - txnoassoc
  - txchit
  - txcmiss
  - txserr
  - txphyerr
  - txphycrs
  - txerror
  - txexptime
  - rxframe
  - rxbyte
  - rxerror
  - rxdropped
  - rxcrc
  - rxnobuf
  - rxnondata
  - rxbadds
  - rxbadcm
  - rxdup
  - rxfragerr
  - rxrunt
  - rxgiant
  - rxnoscb
  - rxbadproto
  - rxbadsrcmac
  - rxrtry
  - date_time
