version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

  __main__:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/main.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  setup:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/setup/setup.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  static_data:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/static_data.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  files_transfer:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/files_transfer.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  results_files_generation:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/result_files_generation.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  info_stations:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/info_stations.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  chanim_stats:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/chanim_stats.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  antenas_tx_rx_stats:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/antenas_tx_rx_stats.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  telnet:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: /home/nico/workspace/Livebox-wifi-stats/wifi_stats/logs/telnet.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

root:
  level: WARN
  handlers: [console]

loggers:

  programs.setup.generate_files:
    level: DEBUG
    handlers: [setup]
    propagate: no

  programs.setup.generate_traffic_config:
    level: DEBUG
    handlers: [setup]
    propagate: no

  programs.setup.initial_transfer_files_to_stations:
    level: DEBUG
    handlers: [setup]
    propagate: no

  __main__:
    level: DEBUG
    handlers: [__main__]
    propagate: no

  programs.chanim_stats:
    level: DEBUG
    handlers: [chanim_stats]
    propagate: no

  programs.tx_rx_stats:
    level: INFO
    handlers: [antenas_tx_rx_stats]
    propagate: no

  programs.files_transfer:
    level: DEBUG
    handlers: [files_transfer]
    propagate: no

  programs.results.traffic_file_generation:
    level: DEBUG
    handlers: [results_files_generation]
    propagate: no

  programs.results.antenas_througput_file_generation:
    level: DEBUG
    handlers: [results_files_generation]
    propagate: no

  programs.calibration.initial_calibrate_stations:
    level: DEBUG
    handlers: [console]
    propagate: no

  programs.calibration.livebox_counters_log:
    level: DEBUG
    handlers: [console]
    propagate: no

  programs.info_connected_stations:
    level: DEBUG
    handlers: [info_stations]
    propagate: no

  programs.static_data:
    level: DEBUG
    handlers: [static_data]
    propagate: no

  common.telnet:
    level: DEBUG
    handlers: [telnet]
    propagate: no
