RADIO_STATS_COLUMNS:
  - BroadcastPacketsReceived
  - BroadcastPacketsSent
  - BytesReceived
  - BytesSent
  - DiscardPacketsReceived
  - DiscardPacketsSent
  - ErrorsReceived
  - ErrorsSent
  - FailedRetransCount
  - MulticastPacketsReceived
  - MulticastPacketsSent
  - MultipleRetryCount
  - Noise
  - PacketsReceived
  - PacketsSent
  - RetransCount
  - RetryCount
  - Temperature
  - UnicastPacketsReceived
  - UnicastPacketsSent
  - UnknownProtoPacketsReceived
  - WmmBytesReceived.AC_BE
  - WmmBytesReceived.AC_BK
  - WmmBytesReceived.AC_VI
  - WmmBytesReceived.AC_VO
  - WmmBytesSent.AC_BE
  - WmmBytesSent.AC_BK
  - WmmBytesSent.AC_VI
  - WmmBytesSent.AC_VO
  - WmmFailedBytesReceived.AC_BE
  - WmmFailedBytesReceived.AC_BK
  - WmmFailedBytesReceived.AC_VI
  - WmmFailedBytesReceived.AC_VO
  - WmmFailedReceived.AC_BE
  - WmmFailedReceived.AC_BK
  - WmmFailedReceived.AC_VI
  - WmmFailedReceived.AC_VO
  - WmmFailedSent.AC_BE
  - WmmFailedSent.AC_BK
  - WmmFailedSent.AC_VI
  - WmmFailedSent.AC_VO
  - WmmFailedbytesSent.AC_BE
  - WmmFailedbytesSent.AC_BK
  - WmmFailedbytesSent.AC_VI
  - WmmFailedbytesSent.AC_VO
  - WmmPacketsReceived.AC_BE
  - WmmPacketsReceived.AC_BK
  - WmmPacketsReceived.AC_VI
  - WmmPacketsReceived.AC_VO
  - WmmPacketsSent.AC_BE
  - WmmPacketsSent.AC_BK
  - WmmPacketsSent.AC_VI
  - WmmPacketsSent.AC_VO
RADIO_AIR_STATS_COLUMNS:
  - FreeTime
  - IntTime
  - Load
  - LongPreambleErrorPercentage
  - Noise
  - NoiseTime
  - ObssTime
  - RxTime
  - ShortPreambleErrorPercentage
  - Timestamp
  - TotalTime
  - TxTime
  - VendorStats.BadPlcp
  - VendorStats.Glitch
