COLUMNS:
  - Active
  - AssociationTime
  - AuthenticationState
  - AvgSignalStrength
  - AvgSignalStrengthByChain
  - Capabilities
  - ChargeableUserId
  - ConnectionDuration
  - DevicePriority
  - DeviceType
  - DisassociationTime
  - DownlinkBandwidth
  - DownlinkMCS
  - DownlinkRateSpec
  - DownlinkShortGuard
  - EncryptionMode
  - FrequencyCapabilities
  - HeCapabilities
  - HtCapabilities
  - Inactive
  - LastDataDownlinkRate
  - LastDataUplinkRate
  - LastStateChange
  - LinkBandwidth
  - MACAddress
  - MUGroupId
  - MUMimoTxPktsCount
  - MUMimoTxPktsPercentage
  - MUUserPositionId
  - MaxBandwidthSupported
  - MaxDownlinkRateReached
  - MaxDownlinkRateSupported
  - MaxRxSpatialStreamsSupported
  - MaxTxSpatialStreamsSupported
  - MaxUplinkRateReached
  - MaxUplinkRateSupported
  - Noise
  - OperatingStandard
  - PowerSave
  - Retransmissions
  - RrmCapabilities
  - RrmOffChannelMaxDuration
  - RrmOnChannelMaxDuration
  - RxBytes
  - RxMulticastPacketCount
  - RxPacketCount
  - RxSupportedHe160MCS
  - RxSupportedHe80x80MCS
  - RxSupportedHeMCS
  - RxSupportedVhtMCS
  - RxUnicastPacketCount
  - Rx_Retransmissions
  - Rx_RetransmissionsFailed
  - SecurityModeEnabled
  - SignalNoiseRatio
  - SignalStrength
  - SignalStrengthByChain
  - SignalStrengthHistory
  - SupportedHtMCS
  - SupportedMCS
  - TxBytes
  - TxErrors
  - TxMulticastPacketCount
  - TxPacketCount
  - TxSupportedHe160MCS
  - TxSupportedHe80x80MCS
  - TxSupportedHeMCS
  - TxSupportedVhtMCS
  - TxUnicastPacketCount
  - Tx_Retransmissions
  - Tx_RetransmissionsFailed
  - UNIIBandsCapabilities
  - UplinkBandwidth
  - UplinkMCS
  - UplinkRateSpec
  - UplinkShortGuard
  - VendorOUI
  - VhtCapabilities
  - EncryptionMode
  - FrequencyCapabilities
  - HeCapabilities
  - HtCapabilities
  - LinkBandwidth
  - RrmCapabilities
  - RrmOffChannelMaxDuration
  - RrmOnChannelMaxDuration
  - RxSupportedHe160MCS
  - RxSupportedHe80x80MCS
  - RxSupportedHeMCS
  - RxSupportedVhtMCS
  - SecurityModeEnabled
  - SupportedHtMCS
  - SupportedMCS
  - TxSupportedHe160MCS
  - TxSupportedHe80x80MCS
  - TxSupportedHeMCS
  - TxSupportedVhtMCS
  - VendorOUI
  - VhtCapabilities
