
FILES_PATH: /home/nico/workspace/Livebox-wifi-stats/files_to_send/
STATIONS:
  - name: GALAXY_6C_C7_EC_2B_2E_D7
    ip: 192.168.1.26
    ssh_user: nico
    ssh_password: nico
    protocol: sftp
    connection_time: 6
    operative_system: Android
    port: 2233
  - name: RPI_E4_5F_01_E8_C1_2E
    ip: 192.168.1.25
    ssh_user: pi
    ssh_password: pi
    protocol: scp
    connection_time: 6
    operative_system: Linux
    port: 22
  - name: HUAWEI_AC_BD_70_27_CA_19
    ip: 192.168.1.15
    ssh_user: nico
    ssh_password: nico
    protocol: sftp
    connection_time: 6
    operative_system: Android
    port: 2233
