
FILES_PATH: /home/nicolas/workspace/Livebox-wifi-stats/files_to_send/
STATIONS:
  - name: RPI 1
    ip: 192.168.1.12
    ssh_user: nico
    ssh_password: nico
    send_interval: 30
  - name: RPI 2
    ip: 192.168.1.13
    ssh_user: nico
    ssh_password: nico
    send_interval: 30

