
FILES_PATH: /home/nico/workspace/Livebox-wifi-stats/files_to_send/
STATIONS:
  - name: GALAXY_6C_C7_EC_2B_2E_D7
    ip: 192.168.1.26
    ssh_user: nico
    ssh_password: nico
    protocol: sftp
    connection_time: 6
    operative_system: Android
    port: 2233
  - name: PC1_Wigreen_78_AF_08_31_B1_18
    ip: 192.168.1.22
    ssh_user: pc1_w
    ssh_password: Wigreen1234
    protocol: scp
    connection_time: 6
    operative_system: Windows
    port: 22
  - name: RPI_E4_5F_01_E8_C1_2E
    ip: 192.168.1.25
    ssh_user: pi
    ssh_password: pi
    protocol: scp
    connection_time: 6
    operative_system: Linux
    port: 22
