
FILES_PATH: /home/pi/workspace/Livebox-wifi-stats/files_to_send/
STATIONS:
  - name: RPI Box
    ip: 192.168.1.27
    ssh_user: nico
    ssh_password: nico
    send_interval_in_secs: 15
  - name: RPI Camera
    ip: 192.168.1.12
    ssh_user: pi
    ssh_password: pi
    send_interval_in_secs: 15
  - name: RPI Relays
    ip: 192.168.1.28
    ssh_user: pi
    ssh_password: pi
    send_interval_in_secs: 15
  - name: RPI Cloud
    ip: 192.168.1.13
    ssh_user: nico
    ssh_password: nico
    send_interval_in_secs: 15

