
FILES_PATH: /home/nico/workspace/Livebox-wifi-stats/files_to_send/st_4/
STATIONS:
  - name: Android Phone 1
    ip: 192.168.1.35
    ssh_user: nico
    ssh_password: nico
    protocol: sftp
    operative_system: Android
    port: 2233
    initial_data_rate_in_kbps: 0
    throughput_increment_in_kbps: 500
    initial_dead_time_in_secs: 10
    transfer_nb_per_step: 1
    send_interval_in_secs: 0.01
  - name: PC1_Wigreen
    ip: 192.168.1.25
    ssh_user: pc1_w
    ssh_password: Wigreen1234
    protocol: scp
    operative_system: Windows
    port: 22
    initial_data_rate_in_kbps: 0
    throughput_increment_in_kbps: 500
    initial_dead_time_in_secs: 10
    transfer_nb_per_step: 1
    send_interval_in_secs: 5
  - name: RPI_E4_5F_01_1E_0A_34
    ip: 192.168.1.18
    ssh_user: nico
    ssh_password: nico
    protocol: scp
    operative_system: Linux
    port: 22
    initial_data_rate_in_kbps: 0
    throughput_increment_in_kbps: 500
    initial_dead_time_in_secs: 10
    transfer_nb_per_step: 1
    send_interval_in_secs: 5
  - name: PC2_Wigreen
    ip: 192.168.1.51
    ssh_user: pc2_w
    ssh_password: Wigreen1234
    protocol: scp
    operative_system: Windows
    port: 22
    initial_data_rate_in_kbps: 0
    throughput_increment_in_kbps: 500
    initial_dead_time_in_secs: 10
    transfer_nb_per_step: 1
    send_interval_in_secs: 5
